package entities

import "time"
import (
	"github.com/google/uuid"
)

type EntityBase struct {
	Id uuid.UUID

	// CreatedAt means the time when the object is created in real life
	CreatedAt time.Time

	// InsertedAt & UpdatedAt are generated by the database
	InsertedAt time.Time
	UpdatedAt  time.Time
}
