package entities

import (
	"github.com/google/uuid"
	"time"
)

type EntityBase struct {
	Id uuid.UUID `gorm:"type:uuid"`

	// CreatedAt means the time when the object is created in real life
	CreatedAt time.Time

	// InsertedAt & UpdatedAt are generated by the database
	InsertedAt time.Time `gorm:"autoCreateTime"`
	UpdatedAt  time.Time `gorm:"autoUpdateTime"`
}

func NewEntityBase(createdAt time.Time) EntityBase {

	return EntityBase{
		Id:        uuid.New(),
		CreatedAt: createdAt}
}
