package entities

import "time"

type EntityBase struct {
	Id string

	// CreatedAt means the time when the object is created in real life
	CreatedAt time.Time

	// InsertedAt & UpdatedAt are generated by the database
	InsertedAt time.Time
	UpdatedAt  time.Time
}
